// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXDW7abdv-N5GKpFzw95Ics5l2TQktOB4',
    appId: '1:442706311818:web:309d885fb98f5c0cef8b73',
    messagingSenderId: '442706311818',
    projectId: 'error404saldo',
    authDomain: 'error404saldo.firebaseapp.com',
    storageBucket: 'error404saldo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUmkpoEtTYdb0j4wgo3hvHq1M0Fzzc6sk',
    appId: '1:442706311818:android:c31a290ca083e348ef8b73',
    messagingSenderId: '442706311818',
    projectId: 'error404saldo',
    storageBucket: 'error404saldo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiULz4Rr-nl1yUt-0Io5gae7zKI15TjkQ',
    appId: '1:442706311818:ios:f87803c717e9e343ef8b73',
    messagingSenderId: '442706311818',
    projectId: 'error404saldo',
    storageBucket: 'error404saldo.firebasestorage.app',
    iosBundleId: 'com.example.controleFinanceiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiULz4Rr-nl1yUt-0Io5gae7zKI15TjkQ',
    appId: '1:442706311818:ios:f87803c717e9e343ef8b73',
    messagingSenderId: '442706311818',
    projectId: 'error404saldo',
    storageBucket: 'error404saldo.firebasestorage.app',
    iosBundleId: 'com.example.controleFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXDW7abdv-N5GKpFzw95Ics5l2TQktOB4',
    appId: '1:442706311818:web:0e3535150143c95cef8b73',
    messagingSenderId: '442706311818',
    projectId: 'error404saldo',
    authDomain: 'error404saldo.firebaseapp.com',
    storageBucket: 'error404saldo.firebasestorage.app',
  );
}
